# Generated by Django 3.1.4 on 2020-12-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mobileverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='mobile_verify',
            field=models.BooleanField(null=True),
        ),
    ]
