# Generated by Django 3.1.4 on 2020-12-31 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_category_produncts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produncts',
            new_name='Product',
        ),
    ]
